data <- read.csv("newMultiData.txt")
y1 <- as.numeric(data$Y1)
y2 <- as.numeric(data$Y2)
x1 <- as.numeric(data$X1)
x2 <- as.numeric(data$X2)
x3 <- as.numeric(data$X3)
x4 <- as.numeric(data$X4)
y1.length <- length(y1)
y2.length <- length(y2)
x1.length <- length(x1)
x2.length <- length(x2)
x3.length <- length(x3)
x4.length <- length(x4)
y1.mean <- mean(y1)
y2.mean <- mean(y2)
x1.mean <- mean(x1)
x2.mean <- mean(x2)
x3.mean <- mean(x3)
x4.mean <- mean(x4)
y1.sd <- sd(y1)
y2.sd <- sd(y2)
x1.sd <- sd(x1)
x2.sd <- sd(x2)
x3.sd <- sd(x3)
x4.sd <- sd(x4)
y1.min <- min(y1)
y2.min <- min(y2)
x1.min <- min(x1)
x2.min <- min(x2)
x3.min <- min(x3)
x4.min <- min(x4)
y1.max <- max(y1)
y2.max <- max(y2)
x1.max <- max(x1)
x2.max <- max(x2)
x3.max <- max(x3)
x4.max <- max(x4)
data.des.stat <- data.frame(N=c(y1.length,y2.length,x1.length,x2.length,x3.length,x4.length), Minimum=c(y1.min,y2.min,x1.min,x2.min,x3.min,x4.min), Maximum=c(y1.max,y2.max,x1.max,x2.max,x3.max,x4.max), Mean=c(y1.mean,y2.mean,x1.mean,x2.mean,x3.mean,x4.mean), std.dev=c(y1.sd,y2.sd,x1.sd,x2.sd,x3.sd,x4.sd))
data.des.stat
row.names(data.des.stat) <- c("Y1","Y2","X1","X2","X3","X4")
data.des.stat
cor(data)
corData <- cor(data)
library(car)
Loading required package: MASS
Loading required package: nnet
scatterplot(y1 ~ x1, data=data)
pairs(~y1+x1+x2+x3, data=data, main="Simple Scatterplot Matrix")
pairs(~y1+x1+x2+x3+x4, data=data, main="Simple Scatterplot Matrix")
pairs(~y2+x1+x2+x3+x4, data=data, main="Simple Scatterplot Matrix")